### ISSUE TITLE
Tabs in Fasta headers create problems

### ISSUE THREAD

**Issue by Thyra** [Dill-PICL/GOMAP-singularity#12]
Tabs in the headers of the input Fasta file create problems in the fanngo step, see issue #11 
Here are some possible solutions
- mention it in the documentation
- have GOMAP check for tabs as early as possible and fail with a clear error message if they are present
- incorporate an input cleaning step into the pipeline, that would also take care of #6 .

**Comment by wkpalan** [comment]
This has been fixed in v1.1 and v1.2
