### ISSUE TITLE
Domain Step

### ISSUE THREAD

**Issue by CFYanarella** [Dill-PICL/GOMAP-singularity#14]
**Describe the bug**
Upon running the domain step there were no obvious errors (besides the fact that the code ran very quickly), upon inspecting the output: 311 .fa files were in ./GOMAP-0.3_GOMAP-input/input/split, while only 10 of each of the .gff3, .tsv, and .xml files were in ./GOMAP-0.3_GOMAP-input/tmp/domain/iprs/split. There should be 311 of each of the three file types in ./tmp/domain/iprs/split.

**Input File**
>PILA_00001
MSNMPMRICMGDMLILPSSEVPIINGVGRGSQGFGFASAPVLNPVLYNPGQLTFSVLQAT
TIPRVYHSTTNLLSDGRVLVAGSNTHLFYTFTGVFPNELRVEAFSPLYLDNSFNARCPQI
TNVPTIVRHGQTCTVVFTVLDAKKTNSGTFVHDSYLSAILDKIDDTDYNTKDTDAVKVLK
GEISLNGDIKPLEVDIDLKEKTNKNNESTSIDEKPNIDHMCSNKQGQLNAEGNSAVTSVM
SDIEYFSYYDDARANLDFFIEHINPYEFRIMQSYVFGDSVPNSLYSDAVHDYVDSTDVSY
GLLWEDDIWQLNENPVIQSDFAWQQQQEFEINGAEFHDIWS
>PILA_00002
MGIANFVHLCLFCCLGGSLCLGAIATATSASVTVTHGNHDPKYKIAMHSADAPFHPEPGQ
DSIEMTGRDGEKYECFLPNHENKGFKESNQQYSSSVTVVTDKQSRTKTPDELLESLNSQC

**GOMAP step that crashed (if applicable)**
Domain Step

**Attach the output files**

**Intermediate outpul file (if applicable)**

**System Details**
Condo2017

**Additional context**

**Comment by wkpalan** [comment]
Can you attach the exact command you used to run the step? If possible please attach the config file used with the pipeline. 

I will be working on this this weekend, and I will check 

Thanks
Kokul

**Comment by wkpalan** [comment]
Also, the GOMAP-singularity has been updated to a new version 1.3 [GOMAP-1.3](https://gomap-singularity.readthedocs.io/en/v1.3/). I think upgrading the existing one to the new one and re-running the new version might fix the issues and make it easier to troubleshoot

**Comment by CFYanarella** [comment]
I have attached the config file (as a text file) and the text file used to submit the job.

Also I am updating to GOMAP-1.3, and I will let you know how that works.

Thank you,
Colleen

[domain.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/3483873/domain.txt)
[config.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/3483877/config.txt)

**Comment by wkpalan** [comment]
Thanks, could you also attach `pine-domain.out`

**Comment by CFYanarella** [comment]
I have attached pine-domain.out as pine-domain.txt.

I also updated to GOMAP-1.3 and had the same issue, except 15 of each of the .gff3, .tsv, and .xml files were produced at the domain step.

[pine-domain.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/3492759/pine-domain.txt)

**Comment by wkpalan** [comment]
Is this on condo?

**Comment by CFYanarella** [comment]
Yes.

**Comment by wkpalan** [comment]
I think the environment modules have changed in Condo, so different modules have to be loaded for the correct singularity version. The default version is 3.1 now and the GOMAP image was build for 2.6.0. 

Please check the commands in the following job file and adapt your script and submit it again. I think it should work. It is working for me on Condo 

[domain.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/3494851/domain.txt)

P.S. Probably best to remove your email from anything you upload to github.

**Comment by wkpalan** [comment]
@C-Yanarella, If this works please comment and close the ticket.

**Comment by CFYanarella** [comment]
I have tried this with both the older version of GOMAP and GOMAP-1.3 and the same problem persists. 

The job for the older version of GOMAP completed without throwing an error.

The job for GOMAP-1.3 failed. From what I can tell there is an error for setnames(x, value). Attached is pine-domain_new.out as a text file.

Thank you again,
Colleen

[pine-domain_new.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/3501513/pine-domain_new.txt)

**Comment by CFYanarella** [comment]
The issue was resolved by altering the commands in the job file as suggested. Further, all of the files that were created during the failed attempts had to be removed before submitting the script to prevent different errors.
