### ISSUE TITLE
Aggregate Failed

### ISSUE THREAD

**Issue by CFYanarella** [Dill-PICL/GOMAP-singularity#15]
**Describe the bug**
The aggregate step failed, due to a non-zero exit code. 

**Input File**

```
>PILA_00001
MSNMPMRICMGDMLILPSSEVPIINGVGRGSQGFGFASAPVLNPVLYNPGQLTFSVLQAT
TIPRVYHSTTNLLSDGRVLVAGSNTHLFYTFTGVFPNELRVEAFSPLYLDNSFNARCPQI
TNVPTIVRHGQTCTVVFTVLDAKKTNSGTFVHDSYLSAILDKIDDTDYNTKDTDAVKVLK
GEISLNGDIKPLEVDIDLKEKTNKNNESTSIDEKPNIDHMCSNKQGQLNAEGNSAVTSVM
SDIEYFSYYDDARANLDFFIEHINPYEFRIMQSYVFGDSVPNSLYSDAVHDYVDSTDVSY
GLLWEDDIWQLNENPVIQSDFAWQQQQEFEINGAEFHDIWS
>PILA_00002
MGIANFVHLCLFCCLGGSLCLGAIATATSASVTVTHGNHDPKYKIAMHSADAPFHPEPGQ
DSIEMTGRDGEKYECFLPNHENKGFKESNQQYSSSVTVVTDKQSRTKTPDELLESLNSQC
```

**GOMAP step that crashed (if applicable)**
Aggregate

**Attach the output files**
```
Running GOMAP --step=aggregate --config=pine2/config.yml
[1] "Reading the input file"
[1] "Converting to GAF 2.0"
[1] "Checking if data/data/go/go.obo.data exists"
[1] "data/data/go/go.obo.data exists so loading R object"
   user  system elapsed 
  3.266   0.104   3.395 
[1] "Writing the outfile"
[1] "Reading the input file"
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 4 columns, inconsistent with item 1 which has 12 columns. To fill missing columns use fill=TRUE.
Calls: pannzer2gaf ... do.call -> <Anonymous> -> rbind -> <Anonymous> -> rbindlist
Execution halted
Running Aggregate Step
Traceback (most recent call last):
  File "./gomap.py", line 103, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 29, in aggregate
    mixed2gaf(config)
  File "/opt/GOMAP/code/pipeline/mixed2gaf.py", line 8, in mixed2gaf
    check_output_and_run("test.pod",command)
  File "/opt/GOMAP/code/utils/basic_utils.py", line 24, in check_output_and_run
    subprocess.check_call(command,stdin=stdin_file,stdout=stdout_file)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', 'code/pipeline/mixed2gaf.r', '/workdir/pine2/GOMAP-0.3_GOMAP-input/0.3_GOMAP-input.all.yml']' returned non-zero exit status 1
```

**System Details**
Condo

**Additional context**
This problem is similar to the one I ran into with barley which was caused by the tabs. The only thing that I think maybe causing the problem is that the fasta format only has IDs and does not have descriptions, but I am not sure.
/work/dillpicl/cfy/GOMAP-singularity-1.3/pine2

**Comment by wkpalan** [comment]
This is definitely a bug, but it only is caused when the input file name includes GO at the start of the name. I am working on a fix, but it won't be read till end of the day tomorrow. It might be easier to you simpler file names without special characters such as `-` or `_` or `GO`. I will update the docs soon as well.

**Comment by CFYanarella** [comment]
Thank you!

**Comment by wkpalan** [comment]
@C-Yanarella 

I have fixed the issue with the code and have pushed new changes. Follow the steps mentioned below in an existing singularity directory to get it working with the new Singularity 3.x.x image format

    git checkout origin/v1.3.1
    module load singularity # This should load singularity 3.1.1 on condo
    ./setup.sh
    ./test.sh

If the test passes then you should be able to run the aggregate step for the pine data that was crashing from before
