### ISSUE TITLE
Mixmeth argot2.5 stuck at merging inputs

### ISSUE THREAD

**Issue by LeilaFattel** [Dill-PICL/GOMAP-singularity#17]
**Describe the bug**
Mixmeth argot2.5 is always stuck at 33% and the jobs are never returned, even though GOMAP shows that this step has been completed.

**Input File**
 >XP_009379762.1
MQRHSAVSCGNGVSNNAVNGASSRDSARVESSFSAPNFSLNLRRQSQLAPYKIKCDKEPL
NCRLGPPDFYPQTPNCPEETLTREYLQTGYKETIEGIEEAREIALCQGSSFSKPEYIVKY
KEALRKRLRAINESRALKRKAGQVYGVPLSGPLVTKAGAFPEQRASNEDSRRKWIEALSQ
QHKRLHSLAEHVPHGYRRKALFEVLIRYNVPLLRATWFIKVTYLNQVRLASSSVSSGTPD
KAQFARSDLWSKDVVEYLQQLLDEIFPKDGSNVPTPVRNQSSQNTMAMSYRAPQKNESFS
SPDAEEPSLHFKWWYMLRLVQWHLAEGLLLPSPIIELVYNQIQEKESPEVLELLFPVLFD
VIESIALSQTYIRMFVELFVRRIHDLSSSCSSSVDTSQKSFLVDAMVEIVRYLVIVVPDT
FVALDCFPLPSCVVPDLRCRNAFLKLHDSADNVQFDTEDAYLRYLSCGYVTSSIQERASN
LSKNVNPILQAHGAAEVLQALDKALMTGDVILAYNSLFEYLSDVAIEERWLEEVSPCLRS
SLKWIGTIGSSVICSIFFLCEWATCNYRDFRTSMPHNLKLTGRNDFSQIYFAVLLLKLKM
EDLYNFAQSRDGNVMALGTNGKTTSDNDSLLDGTAVENAFVLRNNLSSIYYRKSRRDIFR
SPGLLHDVIVCWLDQHEIGKAGSFRGVEIFLLELISNGIFYPPAYVRQLIVSGIMDKNEN
SLDLQRQRRHRRILQQLPGSCLFDLLEEARIAEVPLLHEIVHAYSSERQLLLRGFLSSKS
NHLNSRGDICSIFSLQKDTDHSSSLGDDNHGKVKGQVTEMKALLSCFLHFPHPFSMPIET
SADESQGILKSTLDSLESKVDLTEGTSGCEEFRKRKRKKLIDDRSSALQGFSFNHSDDED
NWWAKKGPKFQESLKVELPSKLTKQTSRGRQKIVRKTQSLAQLAATRIDSSLGASTSHVC
DNKVSCPHHRSVTEGEVPKDVNHMISGRRSDIGKALKQLRLLERRSISIWLLKSIRQLVG
GNERTPSKASNFTDVYSAPVPDDRNTVRWRIGEDELLSILYILDISGDLLSAVKFLIWLL
PKVLCGSRTLVQGVRNSMLPKNRDQVCQVGEAFLLSSLQRYENVLRAADVLPEVLTALVH
RSLTMMTSNGRPSGAVTFAYARYLLKKYKNVTNVLRWEKKFRATCDQRLLAELETGRSVD
DEFMYFSGVPAGITETDEHIRQKINARMSRTGTNMKELVQRHVEGAVHYFYGKERKLSAV
ATPRNHSLEKWDDSYQIAHDIVLGLVDCIRQNGGATPDGDPCVVASAVSAIVGSIGLAIA
KLPDSTASSNYQSFSSSLNSLNCFRHILQIHIFSLCLLKEALGNRLSRVFEIALAAEASS
VISTAFAPGKAHRNQFQLSSEIHDIYQDHSNELLNSSTKLIVGRTAKAAAAVSALVIGAI
VHGVSSLDRMITAFRLKEGLDVLQFIRSARSSSNGISCSIGTMKLDHCIDVYVHWFRLLV
GNCRTVFDGLVAEMLGESYIVALSRLQRVLSLSVVFSPAYSIFAMVIWRPYIFNSNIANH
EDFQLYRSFLVAIGDAIRHKPFRDLFFRNTHGFYDILATDSGDSEFAAMLESHNPDKHLK
TMAFVPLRARLFLNTLIDCKMPAFSVMREDGTWVAGPAEPRSYSEVEGKLLDQLVHVLDT
LQPAKFHWQWVELRLLLNEQALIEKFETHNMSFAEAIRSLSPSADNFVLSESEKKFTEII
LSRIIVRPEAAPLYSEVVHLLGKLLQESLVMDTKWILAGPDVLLGRKSIRQQLIFVAQRK
GFPIKARFWKPWGWSSSLSDATTNRGDKRKFEAISVEEGEVVEESIDVKMFSKVIHNMDA
EGFSPSQQHKTEKALAELILPCIDRSSSELRNLFANELIKQMGAIDQQINTVTPNGFKSS
LNSEASSNKGNSRKGIRGGSPVLGRRPIDSVPPSAAALKISLSLRLQFLLRLLPIIYEDR
NMRQMLAPIILRLLGKRLVYEDADVCPSTIHMDPLKRELDSPIEASLLDHSSDSLFDRLL
AILHGLLSSYKASWLKSKSVTKSAIKARDISAFDREAAENLQNDLDRMELPASIRWRIQT
AMPFLSPSLSFMAPCHLPVLPSVAHTLLQPSNLNPGTHQRSIPAWTYNFPGKSKSSALQD
MDMEIDPWTLLEDGTNSASASNNSSNMGSTNGDHSNLKACCWLKGTVRVRRTDLTYIGPL
DEDS
>XP_009379763.1

**GOMAP step that crashed (if applicable)**
 Mixmeth

**Attach the output files**
No error is given by GOMAP and mixmeth completes. But Argot never returns finished jobs

**System Details**
Condo
/work/#####/####/GOMAP/GOMAP-singularity/banana4

***Additional Comments***
The input file does have ">" at the start of each sequence header, but for some reason isn't showing in the preview.

**Comment by wkpalan** [comment]
@LeilaFattel ,

Could you please attach the input files (fa and config.yaml) to this issue?

Thanks
Kokul

**Comment by LeilaFattel** [comment]
config.yml:
[config.yml.zip](https://github.com/Dill-PICL/GOMAP-singularity/files/5507081/config.yml.zip)
Fasta file:
[banana4.fa.zip](https://github.com/Dill-PICL/GOMAP-singularity/files/5507071/banana4.fa.zip)

**Comment by wkpalan** [comment]
Hi @LeilaFattel,

I have managed to run GOMAP on the banana dataset you have provided on ISU Condo cluster. There were some delays with Argot2  in the `mixmeth` step. 

One of the split files took a long time to complete, but it completed without issues. Once I had received the job completed emails from Argot2.5, then the `aggregate` step worked as expected.  It might have been issues with the Argot2.5 server when you originally ran the step and that's why the job was incomplete.

1. I would recommend running the `aggregate` step once and find the split files for which the results have not been obtained.
```
ls GOMAP-banana/tmp/mixed-meth/argot2.5/results/
banana.2.tsv
banana.2.tsv.zip
banana.3.tsv
banana.3.tsv.zip
banana.4.tsv
banana.4.tsv.zip
banana.5.tsv
banana.5.tsv.zip
banana.6.tsv
banana.6.tsv.zip
banana.7.tsv
banana.7.tsv.zip
banana.8.tsv
banana.8.tsv.zip
banana.9.tsv
banana.9.tsv.zip
banana.10.tsv
banana.10.tsv.zip
```
2. In this example results for *banana.1* is missing. Delete the corresponding submission html file. There could be multiple that need to be deleted.
```
rmGOMAP-banana/tmp/mixed-meth/argot2.5/html/banana.1.insert.html
```

3. Re-run the `mixmeth` step
4. Wait for the **Job COMPLETED!** email.
5. Run the `aggregate` step and the job should complete correctly

Please check [https://bioinformapping.com/gomap/RUNNING.html](https://bioinformapping.com/gomap/RUNNING.html) for up to date instructions for running GOMAP

Let me know if this works.

Thanks

Best
Kokul

**Comment by wkpalan** [comment]
@LeilaFattel,

Did you get a chance to check this out?

Best
Kokul

**Comment by LeilaFattel** [comment]
Hi @wkpalan 

Yes, I tried several times but the jobs submitted to Argot2.5 are still getting stuck at 33%, and I never get the Job Completed! emails back. Also, because of that, I don't get any files in GOMAP-banana/tmp/mixed-meth/argot2.5/results/ after running the aggregate step to rerun the steps as described above. What do you think I should do?

Best,
Leila

**Comment by wkpalan** [comment]
Hi @LeilaFattel ,

I am closing this issue, because we have figured the issue and it has not repeated itself.

Thanks

Best
Kokul
