### ISSUE TITLE
Fanngo error

### ISSUE THREAD

**Issue by kmrasch0217** [Dill-PICL/GOMAP-singularity#18]
**Describe the bug**
Fanngo is failing and this is the error I am receiving error: out of memory or dimension too large for Octave's index type

**Input File**
 >maker_VaccDscaff701_augustus_gene_0.11_mRNA_1
MKENVGNRKQGAASPCAACKLLRRRCAHDCVFAPYFPAEEPQKFASVHKVFGASNVNKML
QELPVHQRGDAVKSMVYEANARVRDPVYGCVGAISSLQHQIDVLQAQLALAQAEVVHMRM
RQFSSISVPPTTDSPENGSPSPSSKLITPSSQTKSFFNMDMVVDHANMGESLWSC
>maker_VaccDscaff701_snap_gene_0.14_mRNA_1
MMSNMDSDKEQFLREFGEDYGYPNAPKSIDEIRATEFKRLDRDGLVYLDHAGTTLYSEIQ
VETIFKGLTTSVYGNPHSQSDSSLASAEIIGEARQQVLDFCNASARDYKCIFTSGATAAL
KLVGEAFPWSTQSTFMYTMENHNSVLGIREYALSKGATSFAIDIEEAAHDGGGYRSPVSS
IKVLQHPVLRRNETTLLEEEPTGNAYNLFAFPSECNFSGSRFSLHLVNTIRDDTERVLEG
SPYCKGRWMVLIDAAKGCATKPPDLSKYQADFVVISFYKIFGYPTGLGALIVRTEAAKLL
>snap_masked_VaccDscaff533_processed_gene_0.3_mRNA_1

**GOMAP step that crashed (if applicable)**
 Fanngo

**Attach the output files**
error: out of memory or dimension too large for Octave's index type

**System Details**
 Condo
 /work/#####/####/GOMAP/GOMAP-singularity/blueberry2

**Additional context**
There is a > in the beginning of every header that is not appearing in the input preview

**Comment by wkpalan** [comment]
Hi @kmrasch0217,

Could you please attach the whole input file here please? Also any log files from the run?

Thanks
Kokul

**Comment by kmrasch0217** [comment]
Hi Kokul,

I am having a hard time attaching or copy and pasting my input and log
files. Would it be possible for me to email the files directly to you? Or
do you have any other suggestions?

Thank you,

Kayla Rasch

**Comment by wkpalan** [comment]
Hey @kmrasch0217,

Could you please send an email to kokul@bioinformapping.com? I will take a look at it over the weekend.

Thanks

Best
Kokul

**Comment by wkpalan** [comment]
Hey @kmrasch0217,

I have fixed this bug and have released v1.3.4. That should take care of this issue.

Thanks

Best
Kokul
