### ISSUE TITLE
GOMAP install

### ISSUE THREAD

**Issue by augsdihh** [Dill-PICL/GOMAP-singularity#19]
**Describe the bug**
INFO:    Downloading shub image
91.2MiB / 91.2MiB [==============================================================================] 100 % 9.2 MiB/s 0s
ERROR: resolveRodsTarget: srcPath /iplant/home/shared/dillpicl/gomap/GOMAP/1.3.3/GOMAP.sif does not exist
ERROR: rsyncUtil: resolveRodsTarget status = -317000 USER_INPUT_PATH_ERR

**System Details**
 - OS: [Ubuntu]
 - Version: [e.g. 20.04.1 LST]
 - Memory Size: [64GB,128GB,256GB]

**Additional context**

**Comment by wkpalan** [comment]
@augsdihh,

I have fixed the issue now. Please do a `git pull` or `git checkout v1.3.4` after cloning the repo and re-run the setup.sh command.

Thanks
Kokul

**Comment by wkpalan** [comment]
@augsdihh  Did this get solved?

**Comment by augsdihh** [comment]
I try your suggestion, but there are also some bug.
![image](https://user-images.githubusercontent.com/67091370/103390764-0dbf3100-4b51-11eb-9cd7-c131858c18b5.png)

**Comment by wkpalan** [comment]
@augsdihh,

Regret to hear about the issues with installation. I have updated the scripts for installation.  Can you run `git pull` again and try downloading the image again. I don't seem to have any issues with downloading and I have tested it in 3 different machines. I have two follow up questions

1. Do you know what version of Singularity you are using? 
2. Incoming network  ports  1247, 20000-21000 and  40000:46000 are open? Cyverse where the image is hosted requires these ports to be open to access the data.

If it's successful you should see something like we see below.

![image](https://user-images.githubusercontent.com/6353590/103394249-48937b80-4af5-11eb-8dea-04b845886dbe.png)

Thanks
Kokul

**Comment by wkpalan** [comment]
Hi @augsdihh ,

Not sure if you are still interested in troubleshooting. Let me know within the next few days if you are.

Thanks
Kokul
