### ISSUE TITLE
Singularity image not available in CyVerse Data Store

### ISSUE THREAD

**Issue by nathanweeks** [Dill-PICL/GOMAP-singularity#2]
docs/INSTALL.rst mentions that iget/irsync can be used to download the GOMAP Singularity image (GOMAP.simg) from the CyVerse Data Store directory that also houses GOMAP-data.tar.gz. The Singularity image is not there---but perhaps Singularity Hub should be the single "official" source for this image, so it doesn't need to be replicated to the Data Store each time after each update? (In that case, the section on fetching the Singularity image from CyVerse can be removed from the documentation)

**Comment by wkpalan** [comment]
I agree, having one release point will make this much easier to manage.
 
I will fix this and other issues/bugs and update the documentation in a minor version release after you run it on your dataset and complete the annotations.

**Comment by wkpalan** [comment]
I have updated the documentation in the latest branch v1.0.2
