### ISSUE TITLE
setup.sh not working, error msg: image path doesn't exists

### ISSUE THREAD

**Issue by Valledor** [Dill-PICL/GOMAP-singularity#20]
**Describe the bug**
When running setup.sh I get this error:
ERROR: pull is only supported for shub URIs
ERROR  : Image path doesn't exists
ABORT  : Retval = 255

**System Details**
 - OS: Ubuntu
 - Version: 18.04
 - Memory Size: 64GB

**Comment by wkpalan** [comment]
Hi,

Could you please provide some more details?

Which version of Singularity you are using and if you have checked out the correct branch (master) or tag (v1.3.4)?

Thanks
Kokul

**Comment by Valledor** [comment]
Hi Kokul,
Singularity version is 2.4.2-dist, and I tried with both branches. My fault. Then
I updated to version 3.5.2, but I cannot go on:

INFO:    Downloading shub image
 109.61 MiB / 109.61 MiB [=======================================================================================================================] 100.00% 8.93 MiB/s 12s
WARNING: failed to set O_CLOEXEC flags on image
WARNING: failed to set O_CLOEXEC flags on image
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available

Thank you,
Luis

**Comment by wkpalan** [comment]
Hi @Valledor,

Sorry to hear about this issue. Can I ask if you are running this in a WSL1 or WSL2 terminal? 

Thanks

Best
Kokul

**Comment by Valledor** [comment]
Yeah! That was the problem, WSL2 is needed. Everything seems to be working fine now.
Thank you so much,
Luis
