### ISSUE TITLE
error message in aggregate step

### ISSUE THREAD

**Issue by michaelabrouk** [Dill-PICL/GOMAP-singularity#25]
**Describe the bug**
I successfully ran all the preliminary steps of GOMAP on a annotation of Barley genomes having 136k genes. But for the aggregate step, I received error message from the Rscript and I have no idea how to resolve it. Thanks for your help.

**Input File**
 >HORVU.VADA.r1.4HG0000010LC.1 
TRRRRRRRRRRRRRRRRRKTRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRTRRRKRRRRLEEEEEEEEEED
>HORVU.VADA.r1.4HG0000020LC.1 
KKKKKKKKKKKKKKKTRIRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRIRRLEEEEEEEEEED
>HORVU.VADA.r1.4HG0000030LC.1 
RRRRRRRRRRRRRNRRRRRRRRRRRRLAAAEEEEEEEEKQEEEEEEEEKKKKKKKKTRRRRTRRRLEEEEEDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
>HORVU.VADA.r1.4HG0000040.1 
MAVHQCTVALFLAVALVAGPAVSHAADAGYAPAAPAGGAPAAAGTKPADAGYTPAAPAGGAPAAPAAAGTKPADAGYTPAAPAGTQPKAMTDEQKLMEQVNNAFKAAVAAAAVVPGPDKYKKFEDTFTPEADRAFSDVLKAGKEGTVNASSSVSSFTAKIGFAHKLAYEAAEGATPEAKYDAFIAILSESLRIIAGTLEVHGVKPATEEVKGPIPAGEMKVVGQIDTAFRIAATAADAAPVNDRFTVFESAFDKAIKETTGGAYAGYKFVPALESGVKKAYAATVAEVPEVKFLVFEAAITRTIAAMAVAAKGAAGAVNAVTSGAATAAGAATSTVNAAAATAAPIAAAAAAAIPKPDAAAAGGYTAPAADAAAAATATPTPAAAAGGYKAPAADAAAAATATPTPAAAAGGYKAPDAAAAAATATPTPAAAAGGYKL
>HORVU.VADA.r1.4HG0000050LC.1 
MKWKTGKLEQAKKGGNANKFSVARSAVPPGWIEGDFLPSTVKEVDILNLVNDGLIAADSWRFPKGEVEPGPREDVAAPNMSTGLPPFTLERPTAPRTLTVLEGEKVQVGILVNALVDLICGGVTGMDLLETFLSRRIQPLQARDHAMWHYSGSEDSTQSHPEEVSTEIMVKWLRSINWACDNPLRAKRVLPFSAENKPPNVELRNMYSPMLDGEQVDIGGESEGDIPDSDYVEDSKDSEDGSEESEGEIQSPPCNESRSKHRQDPAATPSKTLVSSTTNMKRDKAATTKLAEKAAKQPKPDAIQQERRRGPSWAVPPAHQGLVHHLQGLWASPGWAAPPVKTRNPFVIPGTFPVTPKTFR

**GOMAP step that crashed (if applicable)**
aggregate 

**Attach the output files**
 *** caught segfault ***
address 0x557df8c6aea4, cause 'memory not mapped'

 *** caught segfault ***
address 0x557df8c2b074, cause 'memory not mapped'

Traceback:
 1: forderv(firstofeachgroup)
 2: `[.data.table`(data, , rm_red(.SD, aspect, db_object_id, go_obo,     obs_and_alt, .I, unit_size, unit_perc, in_gaf), by = list(aspect,     db_object_id))
 3: data[, rm_red(.SD, aspect, db_object_id, go_obo, obs_and_alt,     .I, unit_size, unit_perc, in_gaf), by = list(aspect, db_object_id)]
 4: remove_redundancy(in_gaf, out_gaf, config)
 5: FUN(X[[i]], ...)
 6: lapply(uniq_datasets, function(in_gaf) {    non_red_dir = paste(workdir, config$data$gaf$non_red_dir,         sep = "")    out_gaf = paste(non_red_dir, "/", basename(in_g
af), sep = "")    if (file.exists(out_gaf) & file.mtime(in_gaf) < file.mtime(out_gaf)) {        flog.warn(paste("The", out_gaf, "exists, So not removing duplicates from",    
         in_gaf))        flog.info(paste("Remove the ", out_gaf, "file to regenerate"))    }    else {        flog.info(paste("The", out_gaf, "missing, So removing duplicates
 from",             in_gaf))        remove_redundancy(in_gaf, out_gaf, config)        flog.info(paste("Completed Removing Redundacy"))    }})
An irrecoverable exception occurred. R is aborting now ...

Traceback:
 1: forderv(firstofeachgroup)
 2: `[.data.table`(data, , rm_red(.SD, aspect, db_object_id, go_obo,     obs_and_alt, .I, unit_size, unit_perc, in_gaf), by = list(aspect,     db_object_id))
 3: data[, rm_red(.SD, aspect, db_object_id, go_obo, obs_and_alt,     .I, unit_size, unit_perc, in_gaf), by = list(aspect, db_object_id)]
 4: remove_redundancy(in_gaf, out_gaf, config)

 *** caught segfault ***
 5: FUN(X[[i]], ...)
 6: lapply(uniq_datasets, function(in_gaf) {    non_red_dir = paste(workdir, config$data$gaf$non_red_dir,         sep = "")    out_gaf = paste(non_red_dir, "/", basename(in_g
af), sep = "")    if (file.exists(out_gaf) & file.mtime(in_gaf) < file.mtime(out_gaf)) {        flog.warn(paste("The", out_gaf, "exists, So not removing duplicates from",    
         in_gaf))        flog.info(paste("Remove the ", out_gaf, "file to regenerate"))    }    else {        flog.info(paste("The", out_gaf, "missing, So removing duplicates
 from",             in_gaf))        remove_redundancy(in_gaf, out_gaf, config)        flog.info(paste("Completed Removing Redundacy"))    }})
address 0x557df8caab04, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...

Traceback:
 1: forderv(firstofeachgroup)
 2: `[.data.table`(data, , rm_red(.SD, aspect, db_object_id, go_obo,     obs_and_alt, .I, unit_size, unit_perc, in_gaf), by = list(aspect,     db_object_id))
 3: data[, rm_red(.SD, aspect, db_object_id, go_obo, obs_and_alt,     .I, unit_size, unit_perc, in_gaf), by = list(aspect, db_object_id)]
 4: remove_redundancy(in_gaf, out_gaf, config)
 5: FUN(X[[i]], ...)
 6: lapply(uniq_datasets, function(in_gaf) {    non_red_dir = paste(workdir, config$data$gaf$non_red_dir,         sep = "")    out_gaf = paste(non_red_dir, "/", basename(in_g
af), sep = "")    if (file.exists(out_gaf) & file.mtime(in_gaf) < file.mtime(out_gaf)) {        flog.warn(paste("The", out_gaf, "exists, So not removing duplicates from",    
         in_gaf))        flog.info(paste("Remove the ", out_gaf, "file to regenerate"))    }    else {        flog.info(paste("The", out_gaf, "missing, So removing duplicates
 from",             in_gaf))Traceback (most recent call last):
  File "./gomap.py", line 103, in <module>
    aggregate(config)
  File "/opt/GOMAP/code/gomap_aggregate.py", line 36, in aggregate
    clean_redundant(config)
  File "/opt/GOMAP/code/pipeline/make_aggregate.py", line 12, in clean_redundant
    check_output_and_run("test.pod",command)
  File "/opt/GOMAP/code/utils/basic_utils.py", line 24, in check_output_and_run
    subprocess.check_call(command,stdin=stdin_file,stdout=stdout_file)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', 'code/pipeline/clean_redundancy.r', '/workdir/GOMAP-Vada_output/Vada_output.all.yml']' returned non-zero exit status -11

**Intermediate outpul file (if applicable)**
Here is the R.log file
INFO [2021-09-27 15:21:37] Processing TAIR
INFO [2021-09-27 15:22:01] Processing uniprot
INFO [2021-10-09 19:25:01] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.Interproscan5.gaf missing, So generating the dataset
INFO [2021-10-11 20:15:33] 0.65
INFO [2021-10-11 20:15:33] 0.3
INFO [2021-10-11 20:15:33] Filtering annotations with follwing score thresholds for  fanngo
INFO [2021-10-11 20:15:33] 0.65 F
INFO [2021-10-11 20:15:33] 0.3 P
INFO [2021-10-14 07:22:39] Generating GAF file from Argot2.5 Results
INFO [2021-10-14 07:22:46] Generating GAF file from PANNZER Results
WARN [2021-10-14 07:28:51] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.fanngo.gaf exists. So not Running converting FANN-GO results
INFO [2021-10-14 07:28:51] Remove the file to reconvert
INFO [2021-10-14 07:28:53] 0.05
INFO [2021-10-14 07:28:53] 0.15
INFO [2021-10-14 07:28:53] 0.15
INFO [2021-10-14 07:28:53] Filtering annotations with follwing score thresholds for  argot2
INFO [2021-10-14 07:28:53] 0.05 C
INFO [2021-10-14 07:28:53] 0.15 F
INFO [2021-10-14 07:28:53] 0.15 P
INFO [2021-10-14 07:29:03] 0.2
INFO [2021-10-14 07:29:03] 0.55
INFO [2021-10-14 07:29:03] 0.4
INFO [2021-10-14 07:29:03] Filtering annotations with follwing score thresholds for  pannzer
INFO [2021-10-14 07:29:03] 0.2 C
INFO [2021-10-14 07:29:03] 0.55 F
INFO [2021-10-14 07:29:03] 0.4 P
WARN [2021-10-14 07:29:16] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf exists. So not filtering FANN-GO results
INFO [2021-10-14 07:29:16] Remove the file to reconvert
INFO [2021-10-14 07:29:17] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:29:21] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.arabidopsis.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.arabidopsis.gaf
INFO [2021-10-14 07:29:22] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.argot2.5.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.argot2.5.gaf
INFO [2021-10-14 07:29:23] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.fanngo.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf
INFO [2021-10-14 07:29:44] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.pannzer.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.pannzer.gaf
INFO [2021-10-14 07:29:56] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.uniprot.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.uniprot.gaf
INFO [2021-10-14 07:29:59] The /workdir/GOMAP-Vada_output/gaf/d.non_red_gaf/Vada_output.Interproscan5.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:30:01] Reading /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:30:02] Checking for anomalies for alt_ids and aspect before removing redundancy

INFO [2021-10-14 07:30:02] Removing Redundancy from  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
WARN [2021-10-14 07:42:57] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.argot2.5.gaf exists. So not Running converting Argot-2.5 results
INFO [2021-10-14 07:42:57] Remove the file to reconvert
WARN [2021-10-14 07:42:57] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.pannzer.gaf exists. So not Running converting PANNZER results
INFO [2021-10-14 07:42:57] Remove the file to reconvert
WARN [2021-10-14 07:42:57] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.fanngo.gaf exists. So not Running converting FANN-GO results
INFO [2021-10-14 07:42:57] Remove the file to reconvert
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.argot2.5.gaf exists. So not filtering Argot-2.5 results
INFO [2021-10-14 07:42:58] Remove the file to reconvert
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.pannzer.gaf exists. So not filtering PANNZER results
INFO [2021-10-14 07:42:58] Remove the file to reconvert
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf exists. So not filtering FANN-GO results
INFO [2021-10-14 07:42:58] Remove the file to reconvert
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf file to regenerate
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.arabidopsis.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.arabidopsis.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.arabidopsis.gaf file to regenerate
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.argot2.5.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.argot2.5.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.argot2.5.gaf file to regenerate
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.fanngo.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.fanngo.gaf file to regenerate
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.pannzer.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.pannzer.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.pannzer.gaf file to regenerate
WARN [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.uniprot.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.uniprot.gaf
INFO [2021-10-14 07:42:58] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.uniprot.gaf file to regenerate
INFO [2021-10-14 07:42:58] The /workdir/GOMAP-Vada_output/gaf/d.non_red_gaf/Vada_output.Interproscan5.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:43:01] Reading /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:43:02] Checking for anomalies for alt_ids and aspect before removing redundancy

INFO [2021-10-14 07:43:02] Removing Redundancy from  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.argot2.5.gaf exists. So not Running converting Argot-2.5 results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.pannzer.gaf exists. So not Running converting PANNZER results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/a.mm_gaf/Vada_output.fanngo.gaf exists. So not Running converting FANN-GO results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.argot2.5.gaf exists. So not filtering Argot-2.5 results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.pannzer.gaf exists. So not filtering PANNZER results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf exists. So not filtering FANN-GO results
INFO [2021-10-14 07:49:00] Remove the file to reconvert
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf file to regenerate
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.arabidopsis.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.arabidopsis.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.arabidopsis.gaf file to regenerate
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.argot2.5.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.argot2.5.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.argot2.5.gaf file to regenerate
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.fanngo.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.fanngo.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.fanngo.gaf file to regenerate
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.pannzer.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.pannzer.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.pannzer.gaf file to regenerate
WARN [2021-10-14 07:49:00] The /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.uniprot.gaf exists, So not removing duplicates from /workdir/GOMAP-Vada_output/gaf/b.raw_gaf/Vada_output.uniprot.gaf
INFO [2021-10-14 07:49:00] Remove the  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.uniprot.gaf file to regenerate
INFO [2021-10-14 07:49:01] The /workdir/GOMAP-Vada_output/gaf/d.non_red_gaf/Vada_output.Interproscan5.gaf missing, So removing duplicates from /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:49:03] Reading /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf
INFO [2021-10-14 07:49:04] Checking for anomalies for alt_ids and aspect before removing redundancy

INFO [2021-10-14 07:49:04] Removing Redundancy from  /workdir/GOMAP-Vada_output/gaf/c.uniq_gaf/Vada_output.Interproscan5.gaf

**System Details**
 - OS: Ubuntu
 - Version: 18.04.6 LTS
 - Memory Size: 1000GB

**Additional context**

**Comment by wkpalan** [comment]
Hey @michaelabrouk ,

Could you please remove the files from the following locations and re-run the aggregate step?  

1.  `[path to output]/GOMAP-Vada_output/gaf/b.raw_gaf/`
2. `[path to output]/GOMAP-Vada_output/gaf/b.uniq_gaf/`


Kokul

**Comment by michaelabrouk** [comment]
Hi @wkpalan ,

Thanks for the advice. I removed the files and now it works. I just obtained the final gaf file.

All the best,
Michael

**Comment by wkpalan** [comment]
You are welcome. I'm glad it was an easy fix...
