### ISSUE TITLE
Error seqsim step

### ISSUE THREAD

**Issue by strawberrylady** [Dill-PICL/GOMAP-singularity#27]
I have been running the first 4 steps of the GOMAP concurrently using Slurm (didn't use mpi). Fanngo has completed, while domain and mixmeth are still running; however, seqsim stopped after almost 2 days with an error. The same error appeared previously when running without using Slurm.

**Attach the output files**
I have attached the seqsim.err and seqsim.out files from the Slurm run as well as the seqsim.log from GOMAP-singularity here. 

**System Details**
GOMAP-singularity was installed on Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-144-generic x86_64), but the Slurm run for seqsim.job used 48 core and 256G memory.

**Additional context**
Whether the Slurm was used or not, the error message were the same as shown in the seqsim.err file.
[Bnz.combine.longestTR-seqsim.log](https://github.com/Dill-PICL/GOMAP-singularity/files/9647707/Bnz.combine.longestTR-seqsim.log)
[seqsim.err.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/9647828/seqsim.err.txt)
[seqsim.out.txt](https://github.com/Dill-PICL/GOMAP-singularity/files/9647830/seqsim.out.txt)

**Comment by wkpalan** [comment]
Hi,

Regret that this comment was not added automatically. I had responded to the email notification and it seems like this was not posted on this thread.

I am looking into this issue. I will work on troubleshooting this for the next couple of weeks and see what I can do. 

Could you please check the file sizes of the output files in the following path
[PATH to DIR]/BnZ_GOMAP/GOMAP-Bnz.combine.longestTR/tmp/seqsim/


Thanks

Best,
Kokul

**Comment by strawberrylady** [comment]
Dear Kokul,

Thank you for looking into this issue! 

There are two directories within the specified path: 
1)There are two files within the tair directory: one (At.TAIR10-vs-Bnz.combine.longestTR.bl.out ) is empty and another one (Bnz.combine.longestTR-vs-At.TAIR10.bl.out) is 2.6M;
2) There are also two files within the uniprot directory: one (Bnz.combine.longestTR-vs-Plant.UniProt.hc.bl.out) is 1.8M, while another one (Plant.UniProt.hc-vs-Bnz.combine.longestTR.bl.out) is empty.

Best regards,
Susanne

**Comment by wkpalan** [comment]
Susanne,

Could you please remove all the files in that directory and try rerunning the seqsim step?

Thanks

Best
Kokul

**Comment by strawberrylady** [comment]
Dear Kokul,

Just removed the files and started the run as you suggested.

Best regards,
Susanne

**Comment by strawberrylady** [comment]
Dear Kokul,

Just to let you know that it failed again. Same error message. Something else is the culprit.

Best regards,
Susanne

**Comment by wkpalan** [comment]
Hi,

I am looking into this issue. I will work on troubleshooting this for the
next couple of weeks and see what I can do.

Could you please check the file sizes of the output files in the following
path
[PATH to DIR]/BnZ_GOMAP/GOMAP-Bnz.combine.longestTR/tmp/seqsim/


Thanks

**Comment by wkpalan** [comment]
Susanne,

Could you please remove all the files in that directory and try rerunning
the seqsim step?

Thanks

Best
Kokul

**Comment by strawberrylady** [comment]
Dear Kokul,

Thank you for looking into the issue. My apologies for the late reply. 

The file sizes of the output files in the specified path are exactly same as previous ones. Should I re-run it again without making any changes? Will give it another try as you suggested.

Best regards,
Susanne
