### ISSUE TITLE
Unsuccessful Argot2.5 submission.

### ISSUE THREAD

**Issue by mwslawinska** [Dill-PICL/GOMAP-singularity#33]
**Describe the bug**

The mixmeth step is completed and in argot2.5/ directory there are .tsv and .tsv.zip files in the blast /directory, .fa, .out, .out.zip in hmmer/ (generated in the mixmeth-preproc step) and .insert.html in html/, results/ is empty. However, I haven't gotten any e-mails from argot that the job was submitted/completed. 

The message I get about the submission: Running GOMAP --step=mixmeth --config=config.yml INFO: Convert SIF file to sandbox... Running mixed-method based annotations Submitting CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.1.tsv.zip and CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.1.hmm.out.zip to Argot2.5 INFO: Cleaning up image...

Based on the html file, the issue is with the taxon ID that can't be inserted when submitting a job: "mysql error: [1048: Column 'taxon_ID' cannot be null] in EXECUTE("INSERT INTO jobs(data_ins,email,descr,taxon_ID,rules,world,type,inf_content,int_confidence,totalScore,status,location) VALUES (NOW(), NULL, NULL, NULL, NULL, NULL, 'batch', NULL, NULL, NULL, 'job scheduled', '0000')")".
However, I have taxon: "3055" in the config file.  @wkpalan, could you maybe give some suggestions how to deal with that?
Is it maybe an issue with the .yml file ("payload: {blast_file: None, descr: None, email: None, filtra: checked, hmmer_file: None,
        inf_content: '0', int_confidence: '0', measure: simgic, rule_system: both,
        tax_id: None, totalScore: '0', w_hypoth: open_world}")?

Additional note: I tried submitting the generated file: blast/.tsv.zip and hmmer/hmm.out.zip files manually to Argot2.5 and I get warnings: "Truncating Blast input since the maximum number of sequences (10001) has been reached!
Truncating HMMer input since the maximum number of sequences (10001) has been reached!". I suppose some of the genes will be missing then - is it an error in the GOMAP pipeline which can be fixed to avoid that?

**Input File**
>Cre18.g802155_4532.1.p pacid=52508487 transcript=Cre18.g802155_4532.1 locus=Cre18.g802155_4532 ID=Cre18.g802155_4532.1.v6.1 annot-version=v6.1 assoLoc=4532_18_91121_TE org=Chlamydomonas.reinhardtii.CC-4532
MCHLWEWDADIVILTETKLGPRTRWLKDCLRLENLAYRTITSTKPGTEHYKRRSAGVLMAVSARYHAGGHLHIPPTPPNLLGHLAHCTIRTPHSIPLHILGVYCPEDMPTRRRIYTYCTSTLKSAAAAGEHVLIGGDFNAVLTAADRTGPLDDADRHHARFVSSHRLQRITEPNGTTSMTYYQARDGHPKAISRIDDILICQHTSNALVAAATEPGGNTPTLKVQPSGGLFDHSSVHIHLPTFPMRLWTAPTGNRTGSTTQPPTGPWPQVVLPIPTSTLEAVRTKIEHTLASPIARLAAALQPASTAIRDQVDRYTTGATNATELDTQLRRDPTVQAPNLDALAEQLHDILKDGLNILVDMCPKKPPRTGAFAPRRISKKIRRAHEELRQLRAAIADNDTLHT
>Cre18.g802156_4532.1.p pacid=52508488 transcript=Cre18.g802156_4532.1 locus=Cre18.g802156_4532 ID=Cre18.g802156_4532.1.v6.1 annot-version=v6.1 assoLoc=4532_18_91136_TE org=Chlamydomonas.reinhardtii.CC-4532
MAIGAILAALCLPALLRQTANITRHVTATAWHRRHLLLWGAALALTLHSLYLNIPDPCSVEKPHMAILGPTVATSLLSANQTKSLLLAHVPHQPHAAHYVKPTLRGALTIGPAAQPAQASMHTRAPTALHWPPNSNNTYREPQRQHFCSVHALNNSLGLAWLDPLDVLSYAKRVHAHLTATQDPNALFWKDCYCPNSGAFSELLLNHYLYHNATISNIFAYPNRKLIMRRTHFPRLNGDISKEKVLENLPVAARTRGFTVHQYTVRHTIAVRYEAGQWRVIDSVNSPIHNTVLHDNTWNTLDGEVWCLDADMQTRKAIYTYCQQVVGRADACGHHLVTAGDFNAVARAHERDSPIDTADRAHQRFLADSGLRPIRGDTTTTAEWSYEQSRPGMAPYHSRIDDILLCPATRAACTEAREYTSTVAGNFDHKPVHAELLAADLQLWPAPQAGARNPAPQQQTQQRWAEVALPVTQKQLAAAAIRLEEALVEATADLHSATRQATQSIEHALTRHSMDPTGYPASVMHRDLAQDTSIQKADINQLAEQLASALDTGLTCLLEECTRKAPFTGKHHTSRSTARALPEVDAANAAAKLRNEIKACQAEHRQLVADRAKAQREAAATALQHTLATRPAQGHKRIFQKEDMERGLPAVRNPETGEVTTDSTSILAILETHFRKLSAPPRGTRTGDFRLPSNATRGYPFEKADATDQFTLDRNRHPDTHSMLPSMADTANFEQCISHLSRNKATGPDGIPNELLRILPSGMKRNLHCILQIMYVKSQIPETWAASETVLLPKPGDALDIKNKRPIALANTCYKLYTSMLTLGIGELAGPLQLFSEAQEGFRAYCNTERQVLNLVHALEDAALFGKDVYAVYVDYSSAFNTIDQDRLLQIMFDLGLPTDLIRAVRNLYAHATTRIRTEHGSTSAIPIERGTVQGDTLSPVLFILFMEPLVRWLHAGGRGYHYGCLTPSENLQYHCSAAAYADDLAALTNSLDDLQVQCDKIASYAEWASLRVNHTKCATTAIWHDKSRSDPNLDGPTGKATLAAMRRNMTNTIKIGTTPVPYFPPTQPSKYLGV

**GOMAP step that crashed (if applicable)**
 mixmeth (specifically Argot2.5)

**Attach the output files**
Attach the output from GOMAP, both std output and std error if both are stored in separate files.

**Intermediate outpul file (if applicable)**
hmmer: #                                                                 --- full sequence ---- --- best 1 domain ---- --- domain number estimation ----
# target name        accession  query name             accession    E-value  score  bias   E-value  score  bias   exp reg clu  ov env dom rep inc description of target
#------------------- ----------   -------------------- ---------- --------- ------ ----- --------- ------ -----   --- --- --- --- --- --- --- --- ---------------------
Exo_endo_phos        PF03372.21 Cre18.g802155_4532.1.p -             0.0052   16.9   0.0    0.0093   16.1   0.0   1.4   1   0   0   1   1   1   1 Endonuclease/Exonuclease/phosphatase family
Exo_endo_phos_2      PF14529.4  Cre18.g802155_4532.1.p -             0.0061   16.3   0.0     0.013   15.2   0.0   1.6   1   0   0   1   1   1   1 Endonuclease-reverse transcriptase
RVT_1                PF00078.25 Cre18.g802156_4532.1.p -            6.1e-36  123.9   0.0   9.8e-36  123.2   0.0   1.4   1   0   0   1   1   1   1 Reverse transcriptase (RNA-dependent DNA polymerase)
SasG_E               PF17041.3  Cre18.g802156_4532.1.p -               0.09   12.7   0.0      0.25   11.3   0.0   1.7   1   0   0   1   1   1   0 E domain
Metal_resist         PF13801.4  Cre18.g802156_4532.1.p -                2.4    8.2  20.5      0.15   12.1   4.9   2.9   2   0   0   2   2   2   0 Heavy-metal resistance
Transposase_21       PF02992.12 Cre03.g198651_4532.1.p -            1.1e-12   47.5   0.0   1.9e-12   46.7   0.0   1.3   1   0   0   1   1   1   1 Transposase family tnp2
DUF4218              PF13960.4  Cre03.g198651_4532.1.p -            3.9e-10   39.4   0.8   7.4e-10   38.5   0.8   1.3   1   0   0   1   1   1   1 Domain of unknown function (DUF4218)

blast: 
Cre18.g802155_4532.1.p  tr|D8UA36|D8UA36_VOLCA  1.07647e-72
Cre18.g802156_4532.1.p  tr|A7U4W3|A7U4W3_9CHLO  5.44337e-55
Cre18.g802156_4532.1.p  tr|Q76IM9|Q76IM9_CIOIN  1.1508e-36
Cre18.g802156_4532.1.p  tr|D8UA36|D8UA36_VOLCA  7.1638e-36
Cre18.g802156_4532.1.p  tr|L8GFH4|L8GFH4_ACACA  1.45122e-35
Cre18.g802156_4532.1.p  tr|A0A1J4KSI3|A0A1J4KSI3_9EUKA  2.60789e-29
Cre18.g802156_4532.1.p  tr|A0A1J4JHK2|A0A1J4JHK2_9EUKA  2.63018e-29
Cre18.g802156_4532.1.p  tr|A0A1J4K7P0|A0A1J4K7P0_9EUKA  2.83956e-29
Cre18.g802156_4532.1.p  tr|A0A1J4K865|A0A1J4K865_9EUKA  3.06867e-29
Cre18.g802156_4532.1.p  tr|A0A0P4VL16|A0A0P4VL16_9HEMI  8.70985e-29

**System Details**
 - OS: [Ubuntu]
 - Version: [4.15.0-88-generic #88-Ubuntu  x86_64]
 - Memory Size: [64GB]

**Additional context**

**Comment by mmtohm** [comment]
Hey, In my opinion, this step is very flawed. Can you try resubmit again and again?

**Comment by mwslawinska** [comment]
Hey @mmtohm, I tried multiple times and it didn't help, what I did in the end was manually dividing the input files for Argot2.5 (to not go over the max. number of sequences) and now I'll try to combine the results into one file and run the aggregate step, let's see if it works.

**Comment by mmtohm** [comment]
Let us know if it work

**Comment by mwslawinska** [comment]
@mmtohm it does work, GOMAP accepts the file with merged results as Argot2.5 results when the name is as expected.

**Comment by wkpalan** [comment]
Hi @mwslawinska,

I think you have reached a resolution. I would like to see your input config file if that can be attached? The default is set to be 5000 sequences per split part. It seems like that was changed, and that was the reason why the input to Argot2.5  had more sequences than expected and errored out.

Regret the delay, finally got the personal laptop fixed and I can look at GOMAP code and test items.

**Comment by mwslawinska** [comment]
Thank you @wkpalan, I used the following config: 
data:
  domain:
    split_path: tmp/domain/iprs/split
    tmpdir: tmp/domain/iprs
data:
  domain:
    split_path: tmp/domain/iprs/split
    tmpdir: tmp/domain/iprs
    tool: {name: Interproscan5, version: 5.25-64.0}
  gaf: {agg_dir: gaf/e.agg_data, mixed_method_dir: gaf/a.mm_gaf, non_red_dir: gaf/d.non_red_gaf,
    raw_dir: gaf/b.raw_gaf, uniq_dir: gaf/c.uniq_gaf}
  go:
    evidence_codes:
      omitted: [IEA, ND, NAS]
    gaf_col_data: {db: GOMAP, db_object_type: gene, db_reference: 'GOMAP:0000', evidence_code: IEA}
    gaf_cols: data/data/cols/gaf_cols.txt
    obo: data/data/go/go.obo
  mixed-method:
    argot2:
      baseurl: http://www.medcomp.medicina.unipd.it/Argot2-5/
      batch_url: http://www.medcomp.medicina.unipd.it/Argot2-5/insert_batch.php
      payload: {blast_file: None, descr: None, email: None, filtra: checked, hmmer_file: None,
        inf_content: '0', int_confidence: '0', measure: simgic, rule_system: both,
        tax_id: None, totalScore: '0', w_hypoth: open_world}
      preprocess: {blast: tmp/mixed-meth/argot2.5/blast, hmmer: tmp/mixed-meth/argot2.5/hmmer,
        html: tmp/mixed-meth/argot2.5/html}
      result_dir: tmp/mixed-meth/argot2.5/results
      score_th: {C: 0.05, F: 0.15, P: 0.15}
    fanngo:
      out_dir: tmp/mixed-meth/fanngo
      score_th: {F: 0.65, P: 0.3}
    pannzer:
      conf_dir: tmp/mixed-meth/pannzer/conf
      preprocess: {blast: tmp/mixed-meth/pannzer/blast}
      result_dir: tmp/mixed-meth/pannzer/results
      score_th: {C: 0.2, F: 0.55, P: 0.4}
    preprocess:
      blast_opts: [-evalue, 10e-10]
      blast_out: tmp/mixed-meth/preprocess/blast
      fa_path: tmp/mixed-meth/preprocess/fa
      hmmerdb: data/data/mixed-meth/pfamdb/Pfam-A.hmm
      num_seqs: '5000'
      small_seqs: '100'
      uniprot_db: data/data/mixed-meth/uniprot/uniprot_2017_07.sel
  seq-sim:
    TAIR:
      basedir: data/data/seq-sim/tair
      basename: At.TAIR10
      metadata: {date: '', species: arabidopsis, version: TAIR10}
      tmpdir: tmp/seq-sim/tair
    uniprot:
      basedir: data/data/seq-sim/uniprot
      basename: Plant.UniProt.hc
      cleaning:
        omit_tax: ['4577']
        sel_tax: ['15368', '29760', '3055', '3218', '3694', '3702', '3847', '39947',
          '4081', '4558']
      metadata: {species: uniprot, version: '2017-07-26'}
      tmpdir: tmp/seq-sim/uniprot
input: {basename: CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly,
  big_split_path: input/big_split, config_file: /workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly/CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.all.yml,
  cpus: 126, email: mslawinska@mpipz.mpg.de, fasta: CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly.fa,
  gomap_dir: /workdir/./GOMAP-CreinhardtiiCC_4532_707_v6_1_protein_primaryTranscriptOnly_IUPAConly,
  mpi: false, num_seqs: 100000, openmpi: false, small_seqs: 100, species: Chlamydomonas
    reinhardtii, split_path: input/split, taxon: '3055', tmpdir: /biodata/dep_psl/grp_rgo/slawinska/chlamy_GOextension/GOMAP,
  workdir: /workdir/.}
logging: {format: '%(levelname)s [%(asctime)s] %(message)s', formatTime: '%Y-%m-%d
    %H:%M', level: DEBUG}
pipeline: {config_file: pipeline.json, dir_struct: config/dirs.yml, name: GOMAP, pipeline_loc: /opt/GOMAP,
  version: v1.3.5}
software:
  blast:
    bin: data/software/blast-2.6.0+/bin
    cols: data/data/cols/blast_cols.txt
    evalue: 10e-10
    opt_params: []
  fanngo: {path: data/software/FANNGO_linux_x64, template: code/fanngo_template.m}
  hmmer: {path: data/software/hmmer-3.1b2-linux-intel-x86_64/binaries}
  iprs:
    cols: data/data/cols/iprs_cols.txt
    options: []
    path: data/software/interproscan-5.25-64.0
  pannzer:
    conf_template: template.conf
    database: {SQL_DB: pannzer, SQL_DB_HOST: localhost, SQL_DB_PASSWORD: '', SQL_DB_PORT: '',
      SQL_DB_SOCKET: /run/mysqld/mysqld.sock, SQL_DB_USER: pannzer}
    path: data/software/PANNZER
