### ISSUE TITLE
setup.sh not working

### ISSUE THREAD

**Issue by jomare1188** [Dill-PICL/GOMAP-singularity#37]
hi, I'm trying to use GOMAP on HPC and I cannot run setup.sh

`./setup.sh`

`FATAL:  While pulling shub image: error fetching image to cache: failed to get manifest for: shub://wkpalan/icommands-cyverse:latest: 503 Service Unavailable` 

when I try to do it manually:
`singularity pull -F icommands.sif shub://wkpalan/icommands-cyverse:latest`

`FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://wkpalan/icommands-cyverse:latest: 503 Service Unavailable`

it seems like Shub is not working
is there another way to download GOMAP singularity image?

**Comment by wkpalan** [comment]
@jomare1188, I have released a fix. Singularity hub (shub) is now defunct and doesn't work any more. I have moved the image to [quay.io](https://quay.io/repository/wkpalan/icommands). Please use `git pull` to get the new branch and try running `setup.sh` again. If the fix works please comment and close this issue.

**Comment by jomare1188** [comment]
hi @wkpalan, I tried as you said and it doesn't work

`./setup.sh`
`FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/wkpalan/icommands: pinging container registry quay.io: Get "https://quay.io/v2/": x509: certificate signed by unknown authority`

**Comment by wkpalan** [comment]
Hoi @jomare1188 ,

I tested it again and it is working fine for me. 

```
singularity pull -F icommands.sif docker://quay.io/wkpalan/icommands
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 41af1b5f0f51 done  
Copying blob 2fcb98792aa8 done  
Copying blob c0421f9c2a6c done  
Copying blob a0f62cac2c10 done  
Copying blob 33fdaf65a45a done  
Copying blob d5e991dde6ce done  
Copying blob 9e41a5fa6c9f done  
Copying blob 4f4fb700ef54 done  
Copying config ba1f3a280b done  
Writing manifest to image destination
Storing signatures
2023/07/22 01:43:37  info unpack layer: sha256:41af1b5f0f51947706ae712999cf098bef968a7799e7cb4bb2268829e62a6ab3
2023/07/22 01:43:38  info unpack layer: sha256:2fcb98792aa869b34ca81c807bef2fa39ed50efde666e6c3ad03f56311f28a31
2023/07/22 01:43:39  info unpack layer: sha256:c0421f9c2a6c4f37dfca13c540fed10d61061afa517b15213623e249ade2973c
2023/07/22 01:43:39  info unpack layer: sha256:a0f62cac2c10e4f404687cfd0d9f0bdbccdac05a204a4d3c53737395bd11bd67
2023/07/22 01:43:39  info unpack layer: sha256:33fdaf65a45ae277a6cd11514b171b8b538ef168d0a6bfe947ae53ca776b0239
2023/07/22 01:43:39  info unpack layer: sha256:d5e991dde6ce91c418cb1d43d9deb1cc8df71b22e44b0a668dd0abcbc15b144d
2023/07/22 01:43:39  info unpack layer: sha256:9e41a5fa6c9f24f56195bfd29f121d4e0bcf7ef0fdca75681615840fc4727584
2023/07/22 01:43:41  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
INFO:    Creating SIF file...
=============================

```
Can you tell me what version of singularity you are using?

Best,
Kokul

**Comment by jomare1188** [comment]
now it's working!
thankyou
