### ISSUE TITLE
Non-IUPAC symbols in the input

### ISSUE THREAD

**Issue by Thyra** [Dill-PICL/GOMAP-singularity#6]
We inadvertently used a FASTA file containing asterixes (*) in the sequence. We didn't notice until the domain step failed, the others seemed to run through fine. We're figuring out now whether the *s had any influence on the other tools (follow [this issue](https://github.com/Dill-PICL/GOMAP-Paper-2019.1/issues/21)).
How should GOMAP handle non-IUPAC symbols? Complain & fail? Try to repair it?

**Comment by wkpalan** [comment]
This has been fixed in v1.1 and v1.2 please see #13  for details for the discussion of how it was fixed
